version: "3.7"
services:
  database:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: kaiser764/sn-project-api
    restart: unless-stopped
    env_file: 
      - .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"