UNKNOWN_ERROR = "An unknown error has occured."
DATABASE_ERROR = "A database error has occurred."

INPUT_INVALID = "Invalid input data."
USER_DOES_EXIST = "User already exists."
USER_DOES_NOT_EXIST = "User does not exists."
USERNAME_LENGTH_INCORRECT = "Username must be between 3 and 32 characters in length."
PASSWORD_LENGTH_INCORRECT = "Passwords must be between 8 and 32 characters in length."
PASSWORD_INCLUDE_UPPERCASE =  "one uppercase character"
PASSWORD_INCLUDE_LOWERCASE =  "one lowercase character"
PASSWORD_INCLUDE_NUMBER =  "one number"
PASSWORD_INCLUDE = "Passwords must be to include: "
PASSWORD_INCORRECT = "The username and/or password you specified are not correct."
SIGNIN_TRY_LATER = "Please try again in 1 minute"